sudo: true

language: node_js

node_js: "10"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - psql -c 'drop database if exists dms_test;' -U postgres
  - psql -c 'create database dms_test;' -U postgres

services:
  - postgresql
script:
  - yarn test
addons:
  postgresql: "9.3"
