# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10
        environment:
          NODE_ENV: test
          POSTGRES_DB: dms_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password

      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_DB: dms_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password


      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: upgrade-yarn
          command: 'sudo yarn upgrade --latest'
      # Download and cache dependencies
      - restore_cache:
          key:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found

      - run:
          name: Install Packages
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      - run:
        name: Setup PSQL Databases
        command: |
          sudo apt install -y postgresql-client
          createdb dms_test -O postgres
          # createdb db_special -O user
      - run tests:
        name: Run Tests
        command: yarn run test


